codecov:
  branch: master

coverage:
  range: 60..80
  round: down
  status:
    project:
      default:
        threshold: 1%
        branches:
          - "!master"
      AppEngine API:
        flags:
          - astarte_appengine_api
      DataUpdaterPlant:
        flags:
          - astarte_data_updater_plant
      Housekeeping:
        flags:
          - astarte_housekeeping
      Housekeeping API:
        flags:
          - astarte_housekeeping_api
      Pairing:
        flags:
          - astarte_pairing
      Pairing API:
        flags:
          - astarte_pairing_api
      Realm Management:
        flags:
          - astarte_realm_management
      Realm Management API:
        flags:
          - astarte_realm_management_api
      Trigger Engine:
        flags:
          - astarte_trigger_engine

ignore:
  - "apps/*/test"

comment:
  layout: "header, diff, files, flags"
  require_changes: yes
  show_carryforward_flags: false

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
        branches:
          - "!master"
      - type: patch
        target: 90%

flags:
  astarte_appengine_api:
    carryforward: true
    paths:
      - apps/astarte_appengine_api
  astarte_data_updater_plant:
    carryforward: true
    paths:
      - apps/astarte_data_updater_plant
  astarte_housekeeping:
    carryforward: true
    paths:
      - apps/astarte_housekeeping
  astarte_housekeeping_api:
    carryforward: true
    paths:
      - apps/astarte_housekeeping_api
  astarte_pairing:
    carryforward: true
    paths:
      - apps/astarte_pairing
  astarte_pairing_api:
    carryforward: true
    paths:
      - apps/astarte_pairing_api
  astarte_realm_management:
    carryforward: true
    paths:
      - apps/astarte_realm_management
  astarte_realm_management_api:
    carryforward: true
    paths:
      - apps/astarte_realm_management_api
  astarte_trigger_engine:
    carryforward: true
    paths:
      - apps/astarte_trigger_engine
