name: Build and Test Astarte Data Updater Plant

on:
  # Run when pushing to stable branches
  push:
    paths:
    - 'apps/astarte_data_updater_plant/**'
    - '.github/workflows/astarte-apps-build-workflow.yaml'
    - '.github/workflows/astarte-data-updater-plant-workflow.yaml'
    - '.github/codecov.yml'
    branches:
    - 'master'
    - 'release-*'
  # Run on branch/tag creation
  create:
  # Run on pull requests for astarte_data_updater_plant
  pull_request:
    paths:
    - 'apps/astarte_data_updater_plant/**'
    - '.github/workflows/astarte-apps-build-workflow.yaml'
    - '.github/workflows/astarte-data-updater-plant-workflow.yaml'
    - '.github/codecov.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  astarte_data_updater_plant:
    uses: ./.github/workflows/astarte-apps-build-workflow.yaml
    with:
      app: "astarte_data_updater_plant"
    secrets: inherit
